<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategory(Category $category){
        return $this
            ->createQueryBuilder('product')
            ->where('product.active = :active')
            ->andWhere('product.category = :category')
            ->setParameter('active',1)
            ->setParameter('category',$category)
            ->getQuery()
            ->getResult();

    }
}
